### ISSUE TITLE
check box should be beside check box name

### ISSUE THREAD

**Issue by prateek-cedcoss** [Makewebbetter/integration-with-mautic-for-wp#19]
os: window10
wp version:5.8
version: 1.0.1
path: frontend
description: when we set the check box in the user registration plugin form, in frontend first name shows then check box
![check box 2021 08 13-16_48_29](https://user-images.githubusercontent.com/86113814/129349751-7f0c6b94-ac8a-4fab-b9a0-5e78464bc29b.png)

![frontend user register check box](https://user-images.githubusercontent.com/86113814/125467021-202ebdd1-9e5f-46ae-862d-66e00d755252.png)

**Comment by pranjalshukla-cedcoss** [comment]
Resolved.

![image](https://user-images.githubusercontent.com/76723013/129903740-ddf01bb8-2033-4de8-a372-c10acdaa066a.png)
